import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "../styles/Home.module.css";
import { Footer } from "@/src/components/Footer";
import { Links } from "@/src/components/Links";
import { Headline } from "@/src/components/Headline";
import { MainBody } from "@/src/components/Main";
import { Header } from "@/src/components/Header";
import { useCounter } from "../hooks/useCounter";
import { useInputArray } from "../hooks/useInputArray";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function About(props) {

  const {
    count,
    isShow,
    handleClick,
    handleShow,
    text,
    array,
    handleChange,
    handleArray,
    
  } = props;
  

  return (
    <>
      <Head>
        <title>about Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <Header />

        {isShow ? <h2>{count}</h2> : null}
        <button className={styles.button} onClick={handleClick}>ボタン</button>
        <button className={styles.button} onClick={handleShow}>
          {isShow ? "非表示" : "表示"}</button>


        <input type="text" value={text} onChange={handleChange} />
        <button className={styles.button} onClick={handleArray}>Add Array</button>

        <ul>
          {array.map((item) => {
            return <li key={item}>{item}</li>
          })}
        </ul>

        
         <MainBody page="about" />

        <Footer />
        
      </div>
    </>
  );
}
