import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "../styles/Home.module.css";
import { Footer } from "@/src/components/Footer";
import { Links } from "@/src/components/Links";
import { Headline } from "@/src/components/Headline";
import { MainBody } from "@/src/components/Main";
import { Header } from "@/src/components/Header";
import { useCallback, useEffect, useState } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export default function Home() {

  const [count, setCount] = useState(1);

  const handleClick = () => {
    setCount((count) => count + 1);
  }

  useEffect(() => {
    //console.log("mount");
    document.body.style.backgroundColor = "lightblue";

    return () => {
    //console.log("unmount");
    document.body.style.backgroundColor = "yellowgreen";

    };
}, []);

  return (
    <>
      <Head>
        <title>index Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <Header />

        <h3>{count}</h3>
        <button className={styles.button} onClick={handleClick}>ボタン</button>

        <MainBody page="index" /> 

        <Footer />
      </div>
    </>
  );
}
